/**
 * Generate th.json (Thai locale) from en.json.
 *
 * Thai translations are provided for the high-traffic, user-facing namespaces
 * (setup, login, nav, common, dashboard, KDS, tables, staff, customers, add-on
 * groups, updates, and the settings language/tab labels). Keys not yet
 * translated fall back to their English value so the file always holds the full
 * key set (translations.test.ts requires locale parity) and the app degrades
 * gracefully rather than showing raw keys.
 *
 * Re-run after adding UI strings:  node scripts/gen-th.cjs
 */
/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'src', 'lib', 'i18n');
const en = JSON.parse(fs.readFileSync(path.join(dir, 'en.json'), 'utf8'));

/** Curated Thai translations, keyed by the same dotted key as en.json. */
const TH = {
  // ── common ──────────────────────────────────────────────────────────────
  'common.add': 'เพิ่ม',
  'common.cancel': 'ยกเลิก',
  'common.close': 'ปิด',
  'common.done': 'เสร็จสิ้น',
  'common.saveFailed': 'บันทึกไม่สำเร็จ ลองอีกครั้ง',
  'common.continue': 'ดำเนินการต่อ',
  'common.delete': 'ลบ',
  'common.edit': 'แก้ไข',
  'common.loading': 'กำลังโหลด...',
  'common.optional': 'ไม่บังคับ',
  'common.save': 'บันทึก',
  'common.saving': 'กำลังบันทึก...',
  'common.search': 'ค้นหา',
  'common.update': 'อัปเดต',
  'common.active': 'ใช้งาน',
  'common.amount': 'จำนวนเงิน',
  'common.appDescription': 'ระบบขายหน้าร้านอัจฉริยะสำหรับร้านอาหาร',
  'common.businessNameFallback': 'ร้าน',
  'common.checkPrinterConnection': 'ตรวจสอบการเชื่อมต่อเครื่องพิมพ์',
  'common.create': 'สร้าง',
  'common.created': 'สร้างเมื่อ:',
  'common.discount': 'ส่วนลด',
  'common.downloadFailed': 'ดาวน์โหลดไม่สำเร็จ',
  'common.failedToDelete': 'ลบไม่สำเร็จ',
  'common.failedToSave': 'บันทึกไม่สำเร็จ',
  'common.import': 'นำเข้า',
  'common.importFailed': 'นำเข้าไม่สำเร็จ',
  'common.inactive': 'ปิดใช้งาน',
  'common.justNow': 'เมื่อสักครู่',
  'common.loadingScreen': 'กำลังโหลด...',
  'common.namePlaceholder': 'ชื่อ',
  'common.no': 'ไม่',
  'common.notAvailable': 'ไม่พร้อมใช้งาน',
  'common.or': 'หรือ',
  'common.percentage': 'เปอร์เซ็นต์',
  'common.pricePlaceholder': 'ราคา',
  'common.print': 'พิมพ์',
  'common.reasonOptional': 'เหตุผล (ไม่บังคับ)',
  'common.remove': 'นำออก',
  'common.removeItem': 'นำรายการออก',
  'common.reprint': 'พิมพ์ซ้ำ',
  'common.restore': 'กู้คืน',
  'common.shareViaWhatsApp': 'แชร์ผ่าน WhatsApp',
  'common.skipped': 'ข้าม (มีอยู่แล้ว):',
  'common.somethingWrong': 'เกิดข้อผิดพลาด',
  'common.subtotal': 'ยอดรวมย่อย',
  'common.tableFallback': 'โต๊ะ',
  'common.tax': 'ภาษี',
  'common.timeHoursMinutesAgo': '{h} ชม. {m} นาทีที่แล้ว',
  'common.timeMinutesAgo': '{m} นาทีที่แล้ว',
  'common.total': 'ยอดรวม',
  'common.yes': 'ใช่',
  'common.reviewFix': 'ตรวจสอบและแก้ไข',
  'common.unknown': 'ไม่ทราบ',

  // ── nav ─────────────────────────────────────────────────────────────────
  'nav.customers': 'ลูกค้า',
  'nav.dashboard': 'แดชบอร์ด',
  'nav.kds': 'จอครัว',
  'nav.orders': 'ออเดอร์',
  'nav.pos': 'ขายหน้าร้าน',
  'nav.products': 'สินค้า',
  'nav.settings': 'ตั้งค่า',
  'nav.support': 'ช่วยเหลือ',
  'nav.whatsapp': 'WhatsApp',
  'nav.staff': 'พนักงาน',
  'nav.tables': 'โต๊ะ',
  'nav.collapse': 'ย่อ',
  'nav.confirmLogout': 'ต้องการออกจากระบบใช่หรือไม่?',
  'nav.logout': 'ออกจากระบบ',
  'nav.logoutTooltip': 'ออกจากระบบ',
  'nav.toggleSidebar': 'สลับแถบเมนู',
  'nav.user': 'ผู้ใช้',
  'nav.serverUnknown': 'ไม่ทราบ',
  'nav.statusError': 'ดึงสถานะไม่สำเร็จ',

  // ── setup wizard ─────────────────────────────────────────────────────────
  'setup.back': 'ย้อนกลับ',
  'setup.welcome': 'ยินดีต้อนรับสู่ FloCafe',
  'setup.tagline': 'สร้างบัญชีเจ้าของร้านและเลือกรูปแบบการตั้งค่าร้าน',
  'setup.chooseLanguage': 'เลือกภาษา',
  'setup.chooseLanguageHint': 'เลือกภาษาสำหรับขั้นตอนตั้งค่าก่อนเลือกประเทศ',
  'setup.languageEnglish': 'อังกฤษ',
  'setup.languageSpanish': 'สเปน',
  'setup.languagePortuguese': 'โปรตุเกส',
  'setup.languageThai': 'ไทย',
  'setup.chooseCountry': 'เลือกประเทศ',
  'setup.chooseCountryHint': 'FloCafe ใช้ประเทศของคุณเพื่อเลือกสกุลเงิน รูปแบบภาษี และข้อมูลตัวอย่างที่เหมาะสม',
  'setup.searchPlaceholder': 'ค้นหาประเทศ สกุลเงิน หรือภาษา…',
  'setup.noMatches': 'ไม่พบประเทศที่ตรงกับ “{query}”',
  'setup.noTaxId': 'ไม่มีเลขประจำตัวผู้เสียภาษี',
  'setup.businessName': 'ชื่อร้านอาหาร',
  'setup.businessNamePlaceholder': 'ชื่อร้านอาหาร',
  'setup.createOwner': 'สร้างบัญชีเจ้าของร้าน',
  'setup.ownerSubtitle': 'ผู้ใช้คนแรกนี้จะได้สิทธิ์เจ้าของเต็มรูปแบบบนเครื่อง POS นี้',
  'setup.ownerName': 'ชื่อเจ้าของร้าน',
  'setup.ownerNamePlaceholder': 'ชื่อเจ้าของร้าน',
  'setup.ownerEmail': 'อีเมลเจ้าของร้าน',
  'setup.ownerEmailPlaceholder': 'owner@restaurant.com',
  'setup.password': 'รหัสผ่าน',
  'setup.passwordPlaceholder': 'กรอกรหัสผ่าน',
  'setup.confirmPassword': 'ยืนยันรหัสผ่าน',
  'setup.confirmPasswordPlaceholder': 'กรอกรหัสผ่านอีกครั้ง',
  'setup.passwordsMatch': 'รหัสผ่านตรงกัน',
  'setup.passwordsMismatch': 'รหัสผ่านไม่ตรงกัน',
  'setup.pinLabel': 'PIN',
  'setup.confirmPinLabel': 'ยืนยัน PIN',
  'setup.continue': 'ดำเนินการต่อ',
  'setup.completeSetup': 'ตั้งค่าเสร็จสิ้น',
  'setup.completeSetupSuccess': 'ตั้งค่าเสร็จแล้ว',
  'setup.completingSetup': 'กำลังตั้งค่า…',
  'setup.errorGeneric': 'ตั้งค่าไม่สำเร็จ',
  'setup.errorNameRequired': 'ต้องกรอกชื่อ อีเมล และรหัสผ่าน',
  'setup.errorPasswordMismatch': 'รหัสผ่านไม่ตรงกัน',
  'setup.errorTermsRequired': 'คุณต้องยอมรับข้อกำหนดและเงื่อนไข นโยบายความเป็นส่วนตัว และข้อจำกัดความรับผิดชอบก่อนดำเนินการต่อ',
  'setup.errorPasswordRequirementsNotMet': 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร และมีตัวพิมพ์ใหญ่ ตัวพิมพ์เล็ก และตัวเลขอย่างละหนึ่งตัว',
  'setup.flowTitle': 'เลือกรูปแบบการให้บริการ',
  'setup.flowSubtitle': 'FloCafe สำหรับร้านอาหารเท่านั้น เลือกรูปแบบการเก็บเงินของสาขานี้',
  'setup.finedineLabel': 'นั่งทานในร้าน',
  'setup.finedineDesc': 'จัดการโต๊ะและเก็บเงินหลังรับประทาน',
  'setup.finedineDetails': 'เหมาะกับร้านที่มีที่นั่ง จัดการโต๊ะ และเก็บเงินหลังเสิร์ฟ',
  'setup.qsrLabel': 'บริการด่วน',
  'setup.qsrDesc': 'สั่งจ่ายที่เคาน์เตอร์',
  'setup.qsrDetails': 'เหมาะกับร้านบริการด่วนที่เก็บเงินก่อนรับอาหาร',
  'setup.setupDataTitle': 'เลือกข้อมูลเริ่มต้น',
  'setup.setupDataSubtitle': 'เลือกปริมาณข้อมูลที่จะสร้างเมื่อเปิดใช้งานครั้งแรก',
  'setup.expressLabel': 'ด่วน',
  'setup.expressBadge': 'แนะนำ',
  'setup.expressDesc': 'ตั้งค่าร้านพร้อมขายแบบพื้นฐาน',
  'setup.demoLabel': 'ตัวอย่าง',
  'setup.demoDesc': 'ข้อมูลตัวอย่างสำหรับฝึกและทดสอบ',
  'setup.emptyLabel': 'ว่างเปล่า',
  'setup.emptyDesc': 'บัญชีเจ้าของและการตั้งค่าที่จำเป็นเท่านั้น',
  'setup.terms': 'ข้อกำหนดและเงื่อนไข',
  'setup.privacy': 'นโยบายความเป็นส่วนตัว',
  'setup.disclaimer': 'ข้อจำกัดความรับผิดชอบ (ไม่มีการรับประกัน)',
  'setup.termsIntro': 'ฉันยอมรับ FloPOS',
  'setup.setMasterPinTitle': 'ตั้งรหัส Master PIN',
  'setup.masterPinRequired': 'ตั้งรหัส Master PIN 4 หลักเพื่อดำเนินการต่อ',
  'setup.cloudTitle': 'บริการคลาวด์',
  'setup.cloudEnableLabel': 'เปิดใช้บริการคลาวด์',
  'setup.cloudUrlLabel': 'URL เซิร์ฟเวอร์คลาวด์',
  'setup.anonymousDataTitle': 'ข้อมูลการใช้งานแบบไม่ระบุตัวตน',

  // ── auth / login ─────────────────────────────────────────────────────────
  'auth.email': 'อีเมล',
  'auth.emailPlaceholder': 'you@business.com',
  'auth.password': 'รหัสผ่าน',
  'auth.passwordPlaceholder': 'กรอกรหัสผ่าน',
  'auth.signIn': 'เข้าสู่ระบบ',
  'auth.signInSuccess': 'เข้าสู่ระบบสำเร็จ!',
  'auth.signInTitle': 'เข้าสู่ระบบเพื่อจัดการร้านของคุณ',
  'auth.signingIn': 'กำลังเข้าสู่ระบบ...',
  'auth.invalidCredentials': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
  'auth.loginFailed': 'เข้าสู่ระบบไม่สำเร็จ — ฐานข้อมูลอาจมีปัญหา',
  'auth.rememberMe': 'จดจำการเข้าสู่ระบบ',
  'auth.forgotPasswordLink': 'ลืมรหัสผ่าน? กู้คืนการเข้าถึง',
  'auth.lockedOut': 'พยายามหลายครั้งเกินไป ลองใหม่ในอีก {minutes} นาที',
  'auth.attemptsRemaining': 'เหลือ {count} ครั้งก่อนถูกล็อก',
  'auth.connectionFailed': 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ ตรวจสอบการเชื่อมต่อแล้วลองใหม่',
  'auth.selectBusiness': 'เลือกร้าน',
  'auth.selectBusinessHint': 'เลือกร้านที่ต้องการจัดการ',
  'auth.createAccount': 'สร้างบัญชี',
  'auth.haveAccount': 'มีบัญชีอยู่แล้ว?',
  'auth.yourName': 'ชื่อของคุณ',
  'auth.confirmPassword': 'ยืนยันรหัสผ่าน',
  'auth.passwordsDoNotMatch': 'รหัสผ่านไม่ตรงกัน',
  'auth.passwordsMatch': 'รหัสผ่านตรงกัน',
  'auth.countryLabel': 'ประเทศ',
  'auth.countryThailand': 'ไทย',
  'auth.countryIndia': 'อินเดีย',
  'auth.businessNameLabel': 'ชื่อร้าน',
  'auth.recoverTitle': 'กู้คืนการเข้าถึง',
  'auth.recoverSubmit': 'รีเซ็ตรหัสผ่าน',
  'auth.recoverBackToLogin': 'กลับไปเข้าสู่ระบบ',
  'auth.recoverPinLabel': 'Master PIN',
  'auth.recoverNewPasswordLabel': 'รหัสผ่านใหม่',
  'auth.recoverConfirmPasswordLabel': 'ยืนยันรหัสผ่านใหม่',
  'auth.recoverSuccess': 'รีเซ็ตรหัสผ่านสำเร็จ เข้าสู่ระบบได้เลย',

  // ── dashboard ────────────────────────────────────────────────────────────
  'dashboard.title': 'แดชบอร์ด',
  'dashboard.todaySales': 'ยอดขายวันนี้',
  'dashboard.sales': 'ยอดขาย',
  'dashboard.orders': 'ออเดอร์',
  'dashboard.ordersCount': '{count} ออเดอร์',
  'dashboard.aov': 'มูลค่าเฉลี่ยต่อออเดอร์',
  'dashboard.avgPrepTime': 'เวลาเตรียมเฉลี่ย',
  'dashboard.busiestDay': 'วันที่ยุ่งที่สุด',
  'dashboard.busiestHour': 'ชั่วโมงที่ยุ่งที่สุด',
  'dashboard.idlestDay': 'วันที่เงียบที่สุด',
  'dashboard.idlestHour': 'ชั่วโมงที่เงียบที่สุด',
  'dashboard.businessPatterns': 'รูปแบบธุรกิจ',
  'dashboard.newCustomers': 'ลูกค้าใหม่',
  'dashboard.noOrdersYet': 'ยังไม่มีออเดอร์',
  'dashboard.noSalesYet': 'ยังไม่มียอดขายวันนี้',
  'dashboard.notEnoughData': 'ข้อมูลยังไม่เพียงพอ',
  'dashboard.pendingOrders': 'ออเดอร์ค้าง',
  'dashboard.paymentMethods': 'วิธีชำระเงิน',
  'dashboard.recentOrders': 'ออเดอร์ล่าสุด',
  'dashboard.runningOrders': 'ออเดอร์ที่กำลังทำ',
  'dashboard.tablesOccupied': 'โต๊ะที่มีลูกค้า',
  'dashboard.topCategories': 'หมวดหมู่ยอดนิยม',
  'dashboard.topProductsToday': 'สินค้าขายดีวันนี้',
  'dashboard.topStaff': 'พนักงานยอดเยี่ยม',
  'dashboard.viewAll': 'ดูทั้งหมด',
  'dashboard.walkIn': 'ลูกค้าทั่วไป',
  'dashboard.selectDate': 'เลือกวันที่',

  // ── KDS (kitchen display) ──────────────────────────────────────────────────
  'kds.title': 'จอแสดงผลครัว',
  'kds.statusWaiting': 'รอ',
  'kds.statusPreparing': 'กำลังทำ',
  'kds.statusReady': 'พร้อมเสิร์ฟ',
  'kds.statusDelivered': 'เสิร์ฟแล้ว',
  'kds.statusVoided': 'ยกเลิก',
  'kds.bump': 'ดันคิว',
  'kds.markAs': 'ทำเครื่องหมายเป็น {status}',
  'kds.backTo': 'กลับไปที่ {status}',
  'kds.itemMarked': 'ทำเครื่องหมายรายการเป็น {status} แล้ว',
  'kds.tableLabel': 'โต๊ะ {name}',
  'kds.ordersActive': '{count} รายการที่ทำอยู่',
  'kds.emptyAll': 'ไม่มีออเดอร์ค้าง 🎉',
  'kds.emptyHint': 'รายการจะปรากฏที่นี่เมื่อสถานะเปลี่ยน',
  'kds.emptyItems': 'ไม่มีรายการ {status}',
  'kds.addonsLabel': 'รายการเสริม',
  'kds.specialInstructionsLabel': 'คำสั่งพิเศษ',
  'kds.connectionLive': 'เรียลไทม์',
  'kds.connectionPolling': 'ดึงข้อมูลทุก 5 วิ',
  'kds.connectionConnecting': 'กำลังเชื่อมต่อ...',
  'kds.updating': 'กำลังอัปเดต…',
  'kds.viewKanban': 'คัมบัง',
  'kds.viewTabs': 'แท็บ',
  'kds.loginSubtitle': 'เข้าสู่ระบบด้วยบัญชีพนักงานครัว',
  'kds.loginHint': 'เฉพาะพ่อครัว ผู้จัดการ หรือเจ้าของเท่านั้นที่เข้าถึงจอครัวได้',
  'kds.authFailed': 'ยืนยันตัวตนไม่สำเร็จ',
  'kds.loginFailed': 'เข้าสู่ระบบไม่สำเร็จ',
  'kds.failedToUpdateItem': 'อัปเดตรายการไม่สำเร็จ',
  'kds.modalOrderNumber': 'ออเดอร์ #{orderNumber}',
  'kds.ttsEnable': 'อ่านออกเสียงออเดอร์ใหม่',
  'kds.ttsDisable': 'ปิดเสียงประกาศออเดอร์',
  'kds.ttsNewOrder': 'ออเดอร์ใหม่ {where} {items}',
  'kds.ttsTableLabel': 'โต๊ะ {table}',

  // ── tables ────────────────────────────────────────────────────────────────
  'tables.title': 'โต๊ะ',
  'tables.add': 'เพิ่มโต๊ะ',
  'tables.addTable': 'เพิ่มโต๊ะ',
  'tables.createTable': 'สร้างโต๊ะ',
  'tables.create': 'สร้าง',
  'tables.creating': 'กำลังสร้าง...',
  'tables.cancel': 'ยกเลิก',
  'tables.capacity': 'ความจุ',
  'tables.capacitySeats': '{count} ที่นั่ง',
  'tables.floor': 'ชั้น',
  'tables.tableName': 'ชื่อ',
  'tables.tableNamePlaceholder': 'เช่น T1, โต๊ะ 1',
  'tables.reserve': 'จอง',
  'tables.reserveTable': 'จองโต๊ะ',
  'tables.reserving': 'กำลังจอง...',
  'tables.markAvailable': 'ทำให้ว่าง',
  'tables.noActiveOrders': 'ไม่มีออเดอร์ที่ทำอยู่',
  'tables.noTablesYet': 'ยังไม่มีโต๊ะ เพิ่มโต๊ะแรกของคุณ!',
  'tables.linkCustomer': 'เชื่อมลูกค้า (ไม่บังคับ)',
  'tables.newCustomer': 'ลูกค้าใหม่',
  'tables.showOrderDetails': 'แสดงรายละเอียดออเดอร์',
  'tables.tableCreated': 'สร้างโต๊ะแล้ว',
  'tables.tableCreateFailed': 'สร้างโต๊ะไม่สำเร็จ',
  'tables.statusAvailable': 'ว่าง',
  'tables.statusOccupied': 'มีลูกค้า',
  'tables.statusReserved': 'จองแล้ว',
  'tables.statusCleaning': 'กำลังทำความสะอาด',
  'tables.statusHeld': 'พักไว้',
  'tables.deactivate': 'ปิดใช้งาน',
  'tables.reactivate': 'เปิดใช้งานอีกครั้ง',
  'tables.searchCustomerPlaceholder': 'ค้นหาด้วยเบอร์โทรหรือชื่อ...',

  // ── staff ──────────────────────────────────────────────────────────────────
  'staff.title': 'พนักงาน',
  'staff.addButton': 'เพิ่มพนักงาน',
  'staff.addedToast': 'เพิ่มพนักงานแล้ว',
  'staff.updatedToast': 'อัปเดตพนักงานแล้ว',
  'staff.updateButton': 'อัปเดต',
  'staff.modalTitleAdd': 'เพิ่มพนักงาน',
  'staff.modalTitleEdit': 'แก้ไขพนักงาน',
  'staff.namePlaceholder': 'ชื่อ',
  'staff.passwordPlaceholder': 'รหัสผ่าน',
  'staff.empty': 'ยังไม่มีพนักงาน',
  'staff.deactivate': 'ปิดใช้งาน',
  'staff.reactivate': 'เปิดใช้งานอีกครั้ง',
  'staff.resetPwButton': 'รีเซ็ตรหัสผ่าน',
  'staff.resetPasswordTitle': 'รีเซ็ตรหัสผ่าน',
  'staff.resetPasswordToast': 'รีเซ็ตรหัสผ่านสำเร็จ',
  'staff.roleOwner': 'เจ้าของ',
  'staff.roleManager': 'ผู้จัดการ',
  'staff.roleCashier': 'แคชเชียร์',
  'staff.roleWaiter': 'พนักงานเสิร์ฟ',
  'staff.roleChef': 'พ่อครัว (จอครัว)',
  'staff.pinSet': '✓ ตั้ง PIN แล้ว',
  'staff.pinPlaceholderAdd': 'PIN (4-6 หลัก)',

  // ── customers ───────────────────────────────────────────────────────────────
  'customer.add': 'เพิ่มลูกค้า',
  'customer.edit': 'แก้ไขลูกค้า',
  'customer.name': 'ชื่อ',
  'customer.phone': 'เบอร์โทร',
  'customer.email': 'อีเมล',
  'customer.loyalty': 'สะสมแต้ม',
  'customer.totalSpent': 'ยอดใช้จ่ายรวม',
  'customer.visits': 'จำนวนครั้งที่มา',
  'customer.update': 'อัปเดต',
  'customer.added': 'เพิ่มลูกค้าแล้ว',
  'customer.updated': 'อัปเดตลูกค้าแล้ว',
  'customer.search': 'ค้นหาด้วยชื่อ เบอร์โทร หรืออีเมล…',
  'customers.empty': 'ไม่พบลูกค้า',
  'customers.columnCustomer': 'ลูกค้า',
  'customers.columnDate': 'วันที่',
  'customers.columnActions': 'การจัดการ',
  'customers.loyaltyLedger': 'ประวัติสะสมแต้ม',
  'customers.noTransactions': 'ยังไม่มีรายการ',
  'customers.totalBalance': 'ยอดคงเหลือรวม',

  // ── add-on groups ───────────────────────────────────────────────────────────
  'addonGroups.title': 'กลุ่มรายการเสริม',
  'addonGroups.addGroup': 'เพิ่มกลุ่ม',
  'addonGroups.editGroup': 'แก้ไขกลุ่ม',
  'addonGroups.noAddonGroups': 'ยังไม่มีกลุ่มรายการเสริม สร้างกลุ่มแรกของคุณ!',
  'addonGroups.selectRange': 'เลือก {min}–{max}',
  'addonGroups.groupCreated': 'สร้างกลุ่มแล้ว',
  'addonGroups.groupUpdated': 'อัปเดตกลุ่มแล้ว',
  'addonGroups.groupDeleted': 'ลบกลุ่มแล้ว',
  'addonGroups.addonAdded': 'เพิ่มรายการเสริมแล้ว',
  'addonGroups.addonUpdated': 'อัปเดตรายการเสริมแล้ว',
  'addonGroups.addonDeleted': 'ลบรายการเสริมแล้ว',

  // ── businessType / update ────────────────────────────────────────────────────
  'businessType.restaurant': 'ร้านอาหาร',
  'update.sectionLabel': 'อัปเดตแอป',
  'update.readyBadge': 'พร้อมอัปเดต',
  'update.downloadingDetail': 'กำลังดาวน์โหลดเวอร์ชัน {version}...',
  'update.versionReady': 'เวอร์ชัน {version} พร้อมติดตั้งแล้ว',
  'update.currentVersion': 'เวอร์ชันปัจจุบัน: {version}',
  'update.restartNow': 'รีสตาร์ทเดี๋ยวนี้',

  // ── status / gerunds ─────────────────────────────────────────────────────────
  'orders.adding': 'กำลังเพิ่ม...',
  'orders.cancelling': 'กำลังยกเลิก...',
  'orders.converting': 'กำลังแปลง...',
  'orders.generating': 'กำลังสร้าง...',
  'orders.linking': 'กำลังเชื่อม...',
  'orders.printing': 'กำลังพิมพ์...',
  'orders.voidingItem': 'กำลังยกเลิก...',
  'pos.placing': 'กำลังสั่ง...',
  'pos.processingPayment': 'กำลังดำเนินการ...',
  'printTest.printing': 'กำลังพิมพ์...',
  'products.taxInclusiveShort': 'รวมภาษี',
  'products.taxExclusiveShort': 'ไม่รวมภาษี',
  'products.wholeMenu': 'เมนูทั้งหมด',

  // ── settings: language + tab labels (rest of settings stays English for now) ──
  'settings.languages': 'ภาษา',
  'settings.status': 'สถานะ',
  'settings.saving': 'กำลังบันทึก...',
  'settings.languageEn': 'English (EN)',
  'settings.languageEs': 'Español (ES)',
  'settings.languagePt': 'Português (PT)',
  'settings.languageTh': 'ไทย (TH)',
  'settings.tabGeneral': 'ทั่วไป',
  'settings.tabKds': 'จอแสดงผลครัว',
  'settings.tabPrinters': 'เครื่องพิมพ์',
  'settings.tabPrinting': 'ตัวเลือกการพิมพ์',
  'settings.tabReceiptsPrinters': 'ใบเสร็จและเครื่องพิมพ์',
  'settings.tabBillTemplate': 'รูปแบบบิล',
  'settings.tabData': 'ข้อมูล',
  'settings.tabDataCloud': 'ข้อมูลและคลาวด์',
  'settings.tabBackupData': 'สำรองและข้อมูล',
  'settings.tabCloud': 'ซิงก์คลาวด์',
  'settings.tabWhatsapp': 'WhatsApp',
  'settings.tabMobileAccess': 'การเข้าถึงมือถือ',
  'settings.tabMoreApps': 'แอปเพิ่มเติม',
  'settings.tabUpdates': 'อัปเดตซอฟต์แวร์',
  'settings.tabAbout': 'เกี่ยวกับ',
  'settings.tablesRequired': 'บังคับเลือกโต๊ะ',
  'settings.kdsTts': 'อ่านออกเสียงออเดอร์ใหม่ที่จอครัว',
  'settings.kdsTtsHint': 'เปิดเสียงประกาศออเดอร์ใหม่เป็นค่าเริ่มต้นทุกจอครัว แต่ละจอยังปิด/เปิดเองได้จากปุ่มลำโพง',
};

// ── POS screen ───────────────────────────────────────────────────────────────
Object.assign(TH, {
  'pos.addCustomer': 'เพิ่มลูกค้า',
  'pos.addToCart': 'เพิ่มลงตะกร้า - {total}',
  'pos.allCategories': 'ทั้งหมด',
  'pos.applyDiscount': 'ใช้ส่วนลด',
  'pos.back': 'ย้อนกลับ',
  'pos.balanceDue': 'ยอดค้างชำระ',
  'pos.cart': 'ตะกร้า',
  'pos.cartEmpty': 'ตะกร้าว่างเปล่า',
  'pos.checkout': 'ชำระเงิน',
  'pos.close': 'ปิด',
  'pos.customer': 'ลูกค้า',
  'pos.customerCreated': 'สร้างลูกค้าแล้ว',
  'pos.customerName': 'ชื่อ',
  'pos.customerUpdated': 'อัปเดตลูกค้าแล้ว',
  'pos.editCustomer': 'แก้ไขลูกค้า',
  'pos.editItem': 'แก้ไขรายการ',
  'pos.saveItemChanges': 'บันทึกการเปลี่ยนแปลง - {total}',
  'pos.delivery': 'จัดส่ง',
  'pos.deliveryAddress': 'ที่อยู่จัดส่ง',
  'pos.discount': 'ส่วนลด',
  'pos.discountRemoved': 'ลบส่วนลดแล้ว',
  'pos.discountUpdated': 'อัปเดตส่วนลดแล้ว',
  'pos.enterName': 'กรอกชื่อ',
  'pos.free': 'ฟรี',
  'pos.freeAddon': 'ฟรี',
  'pos.hold': 'พักออเดอร์',
  'pos.holdButton': 'พักออเดอร์',
  'pos.holdTable': 'พักโต๊ะ',
  'pos.items': 'รายการ',
  'pos.itemCount': '{count, plural, other {# รายการ}}',
  'pos.lowStock': 'ใกล้หมด',
  'pos.outOfStock': 'สินค้าหมด',
  'pos.loyalty': 'สะสมแต้ม',
  'pos.loyaltyWallet': 'กระเป๋าแต้มสะสม',
  'pos.managerPinRequired': 'ต้องใช้ PIN ผู้จัดการสำหรับส่วนลด',
  'pos.noTablesFound': 'ไม่พบโต๊ะ',
  'pos.orderNotesPlaceholder': 'หมายเหตุออเดอร์ (ไม่บังคับ)',
  'pos.orderPaid': 'ชำระออเดอร์ #{number} แล้ว!',
  'pos.orderPlaced': 'สั่งออเดอร์ #{number} แล้ว!',
  'pos.orderTypeDelivery': 'จัดส่ง',
  'pos.orderTypeDineIn': 'ทานในร้าน',
  'pos.orderTypeTakeaway': 'ซื้อกลับ',
  'pos.packaging': 'ค่าบรรจุภัณฑ์',
  'pos.pay': 'ชำระ',
  'pos.payment': 'การชำระเงิน',
  'pos.paymentFailed': 'ชำระเงินไม่สำเร็จ',
  'pos.paymentRecorded': 'บันทึกการชำระเงินแล้ว!',
  'pos.phone': 'เบอร์โทร',
  'pos.placeOrderButton': 'สั่งออเดอร์',
  'pos.placeOrderReady': 'กดสั่งเมื่อพร้อม',
  'pos.placing': 'กำลังสั่ง...',
  'pos.processingPayment': 'กำลังดำเนินการ...',
  'pos.proceedAnyway': 'ดำเนินการต่อ',
  'pos.remove': 'นำออก',
  'pos.required': 'จำเป็น',
  'pos.roundOff': 'ปัดเศษ',
  'pos.searchProducts': 'ค้นหาสินค้า...',
  'pos.selectCustomer': 'เลือกลูกค้า',
  'pos.selectTable': 'เลือกโต๊ะ',
  'pos.selectTableFirst': 'เลือกโต๊ะก่อน',
  'pos.specialInstructions': 'คำสั่งพิเศษ',
  'pos.specialInstructionsPlaceholder': 'เช่น ไม่ใส่หัวหอม เผ็ดพิเศษ...',
  'pos.subtotal': 'ยอดรวมย่อย',
  'pos.tableHeld': 'พักไว้',
  'pos.tableLabel': 'โต๊ะ: {name}',
  'pos.tableOccupied': 'มีลูกค้า',
  'pos.tableReserved': 'จองแล้ว',
  'pos.tableSeats': '{count} ที่นั่ง',
  'pos.tax': 'ภาษี',
  'pos.total': 'ยอดรวม',
  'pos.totalDue': 'ยอดที่ต้องชำระ',
  'pos.addItems': 'เพิ่มรายการ',
  'pos.adding': 'กำลังเพิ่ม…',
  'pos.applyingDiscount': 'กำลังใช้…',
  'pos.billNumber': 'บิล #{number}',
  'pos.changeReturned': 'เงินทอน',
  'pos.flatAmount': 'จำนวนเงินคงที่',
  'pos.generating': 'กำลังสร้าง…',
  'pos.managerPin': 'PIN ผู้จัดการ',
  'pos.noBalance': 'ไม่มียอดค้าง',
  'pos.orderNumber': 'ออเดอร์ #{number}',
  'pos.paid': 'ชำระแล้ว',
  'pos.percentage': 'เปอร์เซ็นต์',
  'pos.splitPayment': 'แยกชำระ',
  'pos.unpaid': 'ยังไม่ชำระ',
  'pos.updateDiscount': 'อัปเดตส่วนลด',
  'pos.calculatingTax': 'กำลังคำนวณภาษี...',
  'pos.confirmPaymentAmount': 'ยืนยันการชำระ · {amount}',
  'pos.creating': 'กำลังสร้าง…',
  'pos.methodCash': 'เงินสด',
  'pos.methodCard': 'บัตร',
  'pos.methodWallet': 'กระเป๋าเงิน',
  'pos.select': 'เลือก',
  'pos.tagVeg': 'มังสวิรัติ',
  'pos.tagNonVeg': 'ไม่ใช่มังสวิรัติ',
  'pos.tagSpicy': 'เผ็ด',
  'pos.tagBestseller': 'ขายดี',
  'pos.tagNewArrival': 'มาใหม่',
  'pos.tagVegan': 'วีแกน',
  'pos.tagGlutenFree': 'ปราศจากกลูเตน',
  'pos.tagOrganic': 'ออร์แกนิก',
  'pos.tagLimited': 'จำนวนจำกัด',
  'pos.pax': 'จำนวนคน',
  'pos.splitCheck': 'แยกบิล',
  'pos.numberOfChecks': 'จำนวนบิล',
  'pos.createChecks': 'สร้างบิล',
});

// ── Orders screen ────────────────────────────────────────────────────────────
Object.assign(TH, {
  'orders.active': 'กำลังทำ',
  'orders.all': 'ทั้งหมด',
  'orders.held': 'พักไว้',
  'orders.balance': 'ยอดคงเหลือ',
  'orders.addItems': 'เพิ่มรายการในออเดอร์',
  'orders.allCategories': 'ทุกหมวดหมู่',
  'orders.allStatuses': 'ทุกสถานะ',
  'orders.allTables': 'ทุกโต๊ะ',
  'orders.allTypes': 'ทุกประเภท',
  'orders.cancel': 'ยกเลิกออเดอร์',
  'orders.cancelReason': 'กรอกเหตุผลการยกเลิก',
  'orders.cancelled': 'ยกเลิกแล้ว',
  'orders.completed': 'เสร็จสิ้น',
  'orders.customerLinked': 'เชื่อมลูกค้าแล้ว',
  'orders.delete': 'ลบ',
  'orders.delivery': 'จัดส่ง',
  'orders.dineIn': 'ทานในร้าน',
  'orders.discountApplied': 'ใช้ส่วนลดสำเร็จ',
  'orders.discountReason': 'กรอกเหตุผลส่วนลด',
  'orders.empty': 'ไม่พบออเดอร์',
  'orders.historyTitle': 'ประวัติออเดอร์',
  'orders.heldEmpty': 'ไม่พบออเดอร์ที่พักไว้',
  'orders.itemRemoved': 'นำรายการออกแล้ว',
  'orders.itemVoided': 'ยกเลิกรายการแล้ว',
  'orders.managerPin': 'กรอก PIN ผู้จัดการ',
  'orders.notesOptional': 'หมายเหตุ (ไม่บังคับ)',
  'orders.online': 'ออนไลน์',
  'orders.pending': 'รอดำเนินการ',
  'orders.preparing': 'กำลังทำ',
  'orders.ready': 'พร้อม',
  'orders.served': 'เสิร์ฟแล้ว',
  'orders.paid': 'ชำระแล้ว',
  'orders.partiallyPaid': 'ชำระบางส่วน',
  'orders.unpaidBadge': 'ยังไม่ชำระ',
  'orders.settled': 'ชำระครบแล้ว',
  'orders.voided': 'ยกเลิกแล้ว',
  'orders.tableAt': 'โต๊ะ {name}',
  'orders.orderCancelled': 'ยกเลิกออเดอร์สำเร็จ',
  'orders.printReceipt': 'พิมพ์ใบเสร็จสำเร็จ',
  'orders.removeItemConfirm': 'นำรายการนี้ออก?',
  'orders.voidItem': 'ยกเลิกรายการ',
  'orders.confirmVoidItem': 'ยืนยันการยกเลิก',
  'orders.resumeInPos': 'ดำเนินต่อใน POS',
  'orders.search': 'ค้นหาด้วยเลขออเดอร์…',
  'orders.searchCustomer': 'ค้นหาด้วยเบอร์โทรหรือชื่อ…',
  'orders.searchMenu': 'ค้นหาเมนู…',
  'orders.takeaway': 'ซื้อกลับ',
  'orders.addItem': 'เพิ่มรายการ',
  'orders.adding': 'กำลังเพิ่ม...',
  'orders.applyDiscount': 'ใช้ส่วนลด',
  'orders.cancelling': 'กำลังยกเลิก...',
  'orders.checkout': 'ชำระเงิน',
  'orders.confirmCancel': 'ยืนยันการยกเลิก',
  'orders.confirmPrint': 'ยืนยันการพิมพ์',
  'orders.confirmReprint': 'ยืนยันการพิมพ์ซ้ำ',
  'orders.converting': 'กำลังแปลง...',
  'orders.convertToTakeaway': 'แปลงเป็นซื้อกลับ',
  'orders.discountAmountLabel': 'จำนวนส่วนลด',
  'orders.discountPercentageLabel': 'เปอร์เซ็นต์ส่วนลด',
  'orders.generating': 'กำลังสร้าง...',
  'orders.itemStatusPending': 'รอดำเนินการ',
  'orders.itemStatusCancelled': 'ยกเลิกแล้ว',
  'orders.itemStatusPreparing': 'กำลังทำ',
  'orders.itemStatusReady': 'พร้อม',
  'orders.itemStatusServed': 'เสิร์ฟแล้ว',
  'orders.itemStatusVoided': 'ยกเลิกแล้ว',
  'orders.itemStatusWaiting': 'รอ',
  'orders.linkCustomer': 'เชื่อมลูกค้า',
  'orders.linking': 'กำลังเชื่อม...',
  'orders.managerPinLabel': 'PIN ผู้จัดการ',
  'orders.newOrder': 'ออเดอร์ใหม่',
  'orders.newTotal': 'ยอดรวมใหม่',
  'orders.noItemsFound': 'ไม่พบรายการ',
  'orders.printHistory': 'ประวัติการพิมพ์',
  'orders.printReceiptTitle': 'พิมพ์ใบเสร็จ',
  'orders.printed': 'พิมพ์แล้ว',
  'orders.printing': 'กำลังพิมพ์...',
  'orders.reopenOrder': 'เปิดออเดอร์อีกครั้ง',
  'orders.viewLogs': 'ดูบันทึก',
  'orders.selectedItems': 'รายการที่เลือก',
});

// ── Settings: Store Details labels (rest of settings still English) ───────────
Object.assign(TH, {
  'settings.general': 'ทั่วไป',
  'settings.storeDetails': 'ข้อมูลร้าน',
  'settings.businessName': 'ชื่อร้าน',
  'settings.country': 'ประเทศ',
  'settings.timezone': 'เขตเวลา',
  'settings.currency': 'สกุลเงิน',
  'settings.currencyAutoFilled': 'สกุลเงิน (เติมอัตโนมัติ)',
  'settings.timezoneAutoFilled': 'เขตเวลา (เติมอัตโนมัติ)',
  'settings.billingType': 'รูปแบบการเก็บเงิน',
  'settings.billingTypePostpaid': 'จ่ายทีหลัง – ชำระตอนเช็คบิล (พักออเดอร์ได้)',
  'settings.billingTypePrepaid': 'จ่ายก่อน – ชำระก่อนรับ (พักไม่ได้)',
  'settings.taxRegistered': 'จดทะเบียนภาษี',
  'settings.phone': 'เบอร์โทร',
  'settings.address': 'ที่อยู่',
  'settings.addressPlaceholder': 'ถนน, เมือง',
  'settings.instagramHandle': 'บัญชี Instagram',
  'settings.instagramHint': 'แสดงบนบิลที่พิมพ์ ถ้ากำหนดไว้',
  'settings.instagramHandleHint': 'แสดงบนบิลที่พิมพ์ ถ้ากำหนดไว้',
  'settings.save': 'บันทึก',
  'settings.saveAll': 'บันทึกทั้งหมด',
  'settings.saveChanges': 'บันทึกการเปลี่ยนแปลง',
  'settings.saveFailed': 'บันทึกไม่สำเร็จ',
  'settings.storeSaved': 'บันทึกข้อมูลร้านแล้ว',
  'settings.tablesRequiredYes': 'ใช่ – บังคับเลือกโต๊ะสำหรับทานในร้าน',
  'settings.tablesRequiredNo': 'ไม่ – เลือกโต๊ะหรือไม่ก็ได้',
});

// ── Products (core) ──────────────────────────────────────────────────────────
Object.assign(TH, {
  'products.wholeMenu': 'เมนูทั้งหมด',
});

// New language-label keys must exist in every locale (parity). en/es/pt/fa get
// them added separately; here we ensure th carries them even if TH above missed.
const out = {};
for (const key of Object.keys(en)) {
  out[key] = Object.prototype.hasOwnProperty.call(TH, key) ? TH[key] : en[key];
}

fs.writeFileSync(path.join(dir, 'th.json'), JSON.stringify(out, null, 2) + '\n', 'utf8');
const translated = Object.keys(en).filter((k) => Object.prototype.hasOwnProperty.call(TH, k)).length;
console.log(`th.json written: ${translated}/${Object.keys(en).length} keys translated, rest English fallback.`);
